### ISSUE TITLE
enhancement: Use real display resolution

### ISSUE THREAD

**Issue by gizmo98** [ricrpi/mupen64plus-video-gles2n64#7]
The current plugin does not respect the real display resolution. It uses resolutions set up in gles2n64.cfg. It is possible to get the current display resolution with the bcm function graphics_get_display_size.  
https://github.com/gizmo98/mupen64plus-video-gles2n64/commit/99c2879f198621c79e4020a44ec176913ff064d0

Tested and runs fine if window width=0 and window height=0.

But what is the right condition to override ini resolution settings? window enable x11=0 or window fullscreen=1? I could also check if the --fullscreen command line option of mupen64plus-core can be tested.

**Comment by ricrpi** [comment]
I have found performance is worse when running with a framebuffer/window size of 1920x1080. My initial hack for the core vidext.c would configure VC to scale up to full screen which worked great without any performance hit. However removing the hack and utilizing SDL2 graphics makes VC scaling more messy/impossible.

Personally I think SDL2 should have a patch to use VC scaling when the window is flagged as full screen. 

P.S. thanks for all the work on the Pi port

**Comment by gizmo98** [comment]
For that reason we change display resolution at runtime to VGA or 720p with tvservice. But at the moment it is a little bit tricky, because if you change the display resolution you have to modify gles2n64.cfg (gles2n64) or mupen64plus.cfg (rice) as well. 

I could add a extra ini option like "use native resolution". So the end user can select his preferred solution.

Or modify SDL2 SDL_rpivideo.c...
If we pass the real display resolution into dst_rect.width and dst_rect.height every render resolution will be upscaled:
https://github.com/spurious/SDL-mirror/blob/master/src/video/raspberry/SDL_rpivideo.c#L248
